language: csharp
solution: OpenTalon.sln

dist: xenial
addons:
  snaps:
  - name: dotnet-sdk
    classic: true
    channel: latest/beta
sudo: required
mono: none
script:
  - sudo snap alias dotnet-sdk.dotnet dotnet
  - dotnet --version